[book]
authors = ["SHUN/ã—ã‚…ã‚“", "ã—ã°ã‘ã‚“ğŸ"]
language = "ja"
multilingual = false
src = "src"
title = "Kickstart Programming"
description = "æƒ…å ±æŠ€è¡“ç ”ç©¶éƒ¨ã®æ–°å…¥éƒ¨å“¡å‘ã‘è³‡æ–™ã§ã™ã€‚"

