[book]
authors = ["SHUN/ã—ã‚…ã‚“", "ã—ã°ã‘ã‚“ğŸ", "Yu"]
language = "ja"
multilingual = false
src = "src"
title = "Kickstart Programming"
description = "æƒ…å ±æŠ€è¡“ç ”ç©¶éƒ¨ã®æ–°å…¥éƒ¨å“¡å‘ã‘è³‡æ–™ã§ã™ã€‚"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/shun-shobon/kickstart-programming"

